<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LIN65004458" failures="1" tests="1" name="cucumber.TestNGTestRunner" time="21.189" errors="0" timestamp="2025-02-10T14:50:36 IST" skipped="0">
  <testcase classname="cucumber.TestNGTestRunner" name="runScenario" time="21.189">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at stepDefinitions.OrderStepDefiniton.checkout_submit_order(OrderStepDefiniton.java:54)
at âœ½.Checkout "IPHONE" and submit the order(file:///C:/Users/kakpavan/eclipse-workspace/SeleniumFramework25/src/test/java/cucumber/SubmitOrder.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- cucumber.TestNGTestRunner -->
